repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff-format
        entry: ruff format
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: mypy --sqlite-cache
        language: system
        pass_filenames: false
